### ISSUE TITLE
Example Build docker compose

### ISSUE THREAD

**Issue by viniciusrm2520** [hackermondev/replit-exporter#8]
compose.yaml

OS: Unraid OS
Docker agent: Dockage
PS.: 2 repls per hour

```
version: "3"
services:
  replit_export:
    image: node:latest
    container_name: replit_export_container
    network_mode: bridge
    working_dir: /app
    environment:
      - NODE_OPTIONS=--no-warnings
    command:
      - /bin/sh
      - -c
      - npm install -g replit-export && replit-export -o /app/output --auth
        <your token replit>
        -c 2
    volumes:
      - /mnt/user/my_folder:/app
networks: {}
```
